### ISSUE TITLE
Use Docker images in Nectar cloud?

### ISSUE THREAD

**Issue by wragge** [GLAM-Workbench/glam-workbench.github.io#38]
I'm generating [Docker images for GLAM Workbench repositories](https://hub.docker.com/u/glamworkbench) from GitHub repos using repo2Docker. They have Jupyter and all necessary Python packages installed and are used on Binder, Reclaim Cloud, and in local Docker installations.

I'm assuming it should be possible to set up the Nectar Cloud to use them as well? I had a brief play but ran into allocation limits (I must have used up my free trial already sometime).

Is it possible to provide something like the Reclaim Cloud 1-click installation for Nectar?

**Comment by andybotting** [comment]
Hey @wragge,

So this sounds like the perfect thing for us to host in our Nectar Research Cloud application catalog. It's got Docker support, so I think it would be easy for us to create an app that basically deploys the Docker image into a virtual machine ready to go. 

We even have a generic Docker app in there where users can simply provide a Docker Hub container ID which would probably work right now. 

Maybe the first step is that we get you some quota on the Nectar Research Cloud. Have you seen our allocation form? https://support.ehelp.edu.au/support/solutions/articles/6000068044-managing-an-allocation

**Comment by wragge** [comment]
Thanks! I've made a request for an allocation.

**Comment by wragge** [comment]
Just adding some notes about what I did yesterday to get the Trove Newspaper Harvester Docker image running.

1. Make sure the right project is selected from the dropdown at the top of the page!
2. Create a key pair - go to Compute -> Key pairs
3. Create new key, and paste in public key, save
4. Go to Applications -> Browse -> Browse local
5. Find Docker Standalone Host, choose ‘quick deploy’
6. Give it a name, then click Next
7. In config: instance medium, make sure key pair is selected, availability zone Tasmania
8. Click Create
9. Click on ‘Deploy this environment’
10. When finished there’s a message like’ Docker Server is up and running at something.something’
11. SSH into server: `ssh -i id_mykey ubuntu@something.something` (ubuntu is default username for image)
12. Create container: `sudo docker run -p 8888:8888 --name trove-newspaper-harvester -v "$PWD":/home/jovyan/work glamworkbench/trove-newspaper-harvester repo2docker-entrypoint jupyter lab --ip 0.0.0.0 --LabApp.default_url='/lab/tree/index.md’`
13. Need to open port — go to Network -> Security groups
14. Find security group for new environment, click manage rules
15. Add a new Ingress rule, TCP, IPv4, Port 8888, IP 0.0.0.0/0 — save
16. Open url: http:/something.something:8888
17. Copy Jupyter token from SSH
18. Paste token in Jupyter interface under ‘Set up a new password’
19. Enter a password, login!
20. Hit Ctrl-C in SSH window to stop Jupyter

Now we have a running Jupyter instance. The password will be saved in the Docker container, so we can stop and restart without all the Jupyter stuff.

1. SSH into environment as above
2. `sudo docker start trove-newspaper-harvester`
3. Go to the url as above, you might need to enter password
4. To stop the container, `sudo docker stop trove-newspaper-harvester` — everything will be saved

To stop instance (but save resources)

1. Go to Project -> Compute -> Instances, select Shut Off


NOT COMPLETED

To create a Volume:

Really should create, attach and mount volume before running Docker. Then I could map the persistent volume to the work directory in Jupyter.

1. Go to Volumes -> Volumes -> Create
2. Once a volume has been created it can be attached to an instance
3. Need to format & mount — see https://tutorials.rc.nectar.org.au/volume-storage/04-format-mount
4. 

QUESTIONS

Can I rsync into stored volume?

**Comment by wragge** [comment]
Yep, setting `JUPYTER_TOKEN` works, and simplifies things a lot -- no SSH to get things going...

1. Make sure the right project is selected from the dropdown at the top of the page!
2. Create a key pair - go to Compute -> Key pairs
3. Create new key, and paste in public key, save
4. Go to Applications -> Browse -> Browse local
5. Find Docker Standalone Host, choose ‘quick deploy’
6. Give it a name, then click Next
7. In config: instance medium, make sure key pair is selected, availability zone Tasmania
8. Click Create
9. Find the Docker Container application and drag to the environment
10. Give container a name, and point to the image on Docker Hub
11. Set environment variables to -- `JUPYTER_TOKEN=mytoken`
12. Port to 8888, Visible outside checked
13. Click create
14. Click on 'Deploy this envirnment'
15. When finished there’s a message like 'Application trove-newspaper-harvester is available at something.something:8888’
16. Go to something.something:8888
17. At the bottom of the login page -- enter the token 'mytoken' and a new password.

This currently opens in classic Jupyter notebook, not lab. This might change automatically because I think repo2docker now uses Lab by default? So next time I update the repo the settings might change.

**Comment by wragge** [comment]
I'll leave this issue here until I've updated all the documentation.

**Comment by wragge** [comment]
This is done! https://updates.timsherratt.org/2021/10/21/glam-workbench-now.html

I'll create a new issue to track available repositories.
